// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Create user
 * @tags user
 * @see http://localhost:3000/swagger#/user/createUser
 */
export const userPostApi = new RequestBuilder<userPostApi.Req, userPostApi.Res>(
  {
    url: "/user",
    method: "post",
  },
);

export namespace userPostApi {
  export interface Req {}

  export type Res = any;
}
