packages:
  - 'packages/*'
  - 'example/*'
  - 'docs'
onlyBuiltDependencies:
  - lefthook
  - sharp
ignoredBuiltDependencies:
  - esbuild
catalog:
  '@types/debug': ^4.1.7
  '@types/node': ^25
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  es-toolkit: ^1.50.0
  oxfmt: ^0.61.0
  react: ^19.2.8
  react-dom: ^19.2.8
  tsdown: ^0.22.14
  typescript: ^7.0.2
  vite: ^8.2.0
  vitest: 4.1.10
