[package]
name = "s_swc_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[profile.release]
lto = true

[dependencies]
serde = "1"
swc_core = { version = "0.25", features = ["plugin_transform","ecma_parser", "ecma_quote","ecma_utils"] }
tracing = "0.1.32"
regex     = "1"


[dev-dependencies]
testing = "0.30.1"

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
