[package]
name = "s_swc_plugin"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
swc_core = { workspace = true, features = [
    "ecma_plugin_transform",
] }
tracing = { workspace = true,  features = ["release_max_level_info"] }
s_swc_visitor = { path = "../swc_visitor" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
testing = { workspace = true }
swc_core = { workspace = true, features = [
    "ecma_plugin_transform",
    "ecma_parser",
] }
[profile.release]
lto = true
strip = true
# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
