// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Finds Pets by tags
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/findPetsByTags
 */
export const petFindByTagsGetApi = new RequestBuilder<
  petFindByTagsGetApi.Req,
  petFindByTagsGetApi.Res
>({
  url: "/pet/findByTags",
  method: "get",
});

export namespace petFindByTagsGetApi {
  export interface Req {}

  export type Res = any;
}
