// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Delete purchase order by ID
 * @tags store
 * @see http://localhost:3000/swagger#/store/deleteOrder
 */
export const storeOrderOrderIdDeleteApi = new RequestBuilder<
  storeOrderOrderIdDeleteApi.Req,
  storeOrderOrderIdDeleteApi.Res
>({
  url: "/store/order/{orderId}",
  method: "delete",
  urlPathParams: ["orderId"],
});

export namespace storeOrderOrderIdDeleteApi {
  export interface Req {}

  export type Res = any;
}
