// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Find purchase order by ID
 * @tags store
 * @see http://localhost:3000/swagger#/store/getOrderById
 */
export const storeOrderOrderIdGetApi = new RequestBuilder<
  storeOrderOrderIdGetApi.Req,
  storeOrderOrderIdGetApi.Res
>({
  url: "/store/order/{orderId}",
  method: "get",
  urlPathParams: ["orderId"],
});

export namespace storeOrderOrderIdGetApi {
  export interface Req {}

  export type Res = any;
}
