/// this file is generated by gen_semi_ui_hashmap.rs
/// do not modify it manually
use swc_core::common::collections::AHashMap;
fn get_semi_ui_map() -> AHashMap<String, String> {
    let mut map = AHashMap::new();
    map.insert("Avatar", "@douyinfe/semi-ui/lib/es/avatar");
    map.insert("Collapsible", "@douyinfe/semi-ui/lib/es/collapsible");
    map.insert("Nav", "@douyinfe/semi-ui/lib/es/navigation");
    map.insert("ButtonGroup", "@douyinfe/semi-ui/lib/es/button/buttonGroup");
    map.insert(
        "DropdownMenu",
        "@douyinfe/semi-ui/lib/es/dropdown/dropdownMenu",
    );
    map.insert("Select", "@douyinfe/semi-ui/lib/es/select");
    map.insert("TagInput", "@douyinfe/semi-ui/lib/es/tagInput");
    map.insert("ArrayField", "@douyinfe/semi-ui/lib/es/form");
    map.insert("Tree", "@douyinfe/semi-ui/lib/es/tree");
    map.insert("NavItem", "@douyinfe/semi-ui/lib/es/navigation/Item");
    map.insert("TagGroup", "@douyinfe/semi-ui/lib/es/tag/group");
    map.insert("InputGroup", "@douyinfe/semi-ui/lib/es/input/inputGroup");
    map.insert("Badge", "@douyinfe/semi-ui/lib/es/badge");
    map.insert("AutoComplete", "@douyinfe/semi-ui/lib/es/autoComplete");
    map.insert("Empty", "@douyinfe/semi-ui/lib/es/empty");
    map.insert("SubNav", "@douyinfe/semi-ui/lib/es/navigation/SubNav");
    map.insert("Popover", "@douyinfe/semi-ui/lib/es/popover");
    map.insert("Steps", "@douyinfe/semi-ui/lib/es/steps");
    map.insert("Banner", "@douyinfe/semi-ui/lib/es/banner");
    map.insert("InputNumber", "@douyinfe/semi-ui/lib/es/inputNumber");
    map.insert("AvatarGroup", "@douyinfe/semi-ui/lib/es/avatar/avatarGroup");
    map.insert("Highlight", "@douyinfe/semi-ui/lib/es/highlight");
    map.insert("DatePicker", "@douyinfe/semi-ui/lib/es/datePicker");
    map.insert("IconButton", "@douyinfe/semi-ui/lib/es/iconButton");
    map.insert("ScrollList", "@douyinfe/semi-ui/lib/es/scrollList");
    map.insert(
        "ScrollItem",
        "@douyinfe/semi-ui/lib/es/scrollList/scrollItem",
    );
    map.insert("Transfer", "@douyinfe/semi-ui/lib/es/transfer");
    map.insert("useFormApi", "@douyinfe/semi-ui/lib/es/form");
    map.insert("withFormApi", "@douyinfe/semi-ui/lib/es/form");
    map.insert("Tag", "@douyinfe/semi-ui/lib/es/tag");
    map.insert("Modal", "@douyinfe/semi-ui/lib/es/modal");
    map.insert("TreeSelect", "@douyinfe/semi-ui/lib/es/treeSelect");
    map.insert("withField", "@douyinfe/semi-ui/lib/es/form");
    map.insert("Typography", "@douyinfe/semi-ui/lib/es/typography");
    map.insert("Image", "@douyinfe/semi-ui/lib/es/image");
    map.insert(
        "DropdownDivider",
        "@douyinfe/semi-ui/lib/es/dropdown/dropdownDivider",
    );
    map.insert("TabPane", "@douyinfe/semi-ui/lib/es/tabs/TabPane");
    map.insert(
        "CheckboxGroup",
        "@douyinfe/semi-ui/lib/es/checkbox/checkboxGroup",
    );
    map.insert("CardGroup", "@douyinfe/semi-ui/lib/es/card/cardGroup");
    map.insert("Collapse", "@douyinfe/semi-ui/lib/es/collapse");
    map.insert("Slider", "@douyinfe/semi-ui/lib/es/slider");
    map.insert("ConfigProvider", "@douyinfe/semi-ui/lib/es/configProvider");
    map.insert("OverflowList", "@douyinfe/semi-ui/lib/es/overflowList");
    map.insert("withFormState", "@douyinfe/semi-ui/lib/es/form");
    map.insert("TimePicker", "@douyinfe/semi-ui/lib/es/timePicker");
    map.insert("Col", "@douyinfe/semi-ui/lib/es/grid");
    map.insert(
        "LocaleProvider",
        "@douyinfe/semi-ui/lib/es/locale/localeProvider",
    );
    map.insert("List", "@douyinfe/semi-ui/lib/es/list");
    map.insert("Checkbox", "@douyinfe/semi-ui/lib/es/checkbox");
    map.insert("Carousel", "@douyinfe/semi-ui/lib/es/carousel");
    map.insert(
        "LocaleConsumer",
        "@douyinfe/semi-ui/lib/es/locale/localeConsumer",
    );
    map.insert("Descriptions", "@douyinfe/semi-ui/lib/es/descriptions");
    map.insert(
        "SplitButtonGroup",
        "@douyinfe/semi-ui/lib/es/button/splitButtonGroup",
    );
    map.insert("Timeline", "@douyinfe/semi-ui/lib/es/timeline");
    map.insert("useFieldApi", "@douyinfe/semi-ui/lib/es/form");
    map.insert("Table", "@douyinfe/semi-ui/lib/es/table");
    map.insert("TextArea", "@douyinfe/semi-ui/lib/es/input/textarea");
    map.insert("Switch", "@douyinfe/semi-ui/lib/es/switch");
    map.insert("Tabs", "@douyinfe/semi-ui/lib/es/tabs");
    map.insert("Rating", "@douyinfe/semi-ui/lib/es/rating");
    map.insert("Layout", "@douyinfe/semi-ui/lib/es/layout");
    map.insert("Space", "@douyinfe/semi-ui/lib/es/space");
    map.insert("Button", "@douyinfe/semi-ui/lib/es/button");
    map.insert("ImagePreview", "@douyinfe/semi-ui/lib/es/image");
    map.insert("Calendar", "@douyinfe/semi-ui/lib/es/calendar");
    map.insert("Pagination", "@douyinfe/semi-ui/lib/es/pagination");
    map.insert("Cascader", "@douyinfe/semi-ui/lib/es/cascader");
    map.insert("Divider", "@douyinfe/semi-ui/lib/es/divider");
    map.insert("Dropdown", "@douyinfe/semi-ui/lib/es/dropdown");
    map.insert("Tooltip", "@douyinfe/semi-ui/lib/es/tooltip");
    map.insert("useFieldState", "@douyinfe/semi-ui/lib/es/form");
    map.insert("Input", "@douyinfe/semi-ui/lib/es/input");
    map.insert("Toast", "@douyinfe/semi-ui/lib/es/toast");
    map.insert("Breadcrumb", "@douyinfe/semi-ui/lib/es/breadcrumb");
    map.insert(
        "DropdownItem",
        "@douyinfe/semi-ui/lib/es/dropdown/dropdownItem",
    );
    map.insert("RadioGroup", "@douyinfe/semi-ui/lib/es/radio/radioGroup");
    map.insert("Icon", "@douyinfe/semi-ui/lib/es/icons");
    map.insert("Skeleton", "@douyinfe/semi-ui/lib/es/skeleton");
    map.insert("BackTop", "@douyinfe/semi-ui/lib/es/backtop");
    map.insert("Radio", "@douyinfe/semi-ui/lib/es/radio");
    map.insert("Progress", "@douyinfe/semi-ui/lib/es/progress");
    map.insert("Anchor", "@douyinfe/semi-ui/lib/es/anchor");
    map.insert("Row", "@douyinfe/semi-ui/lib/es/grid");
    map.insert("Popconfirm", "@douyinfe/semi-ui/lib/es/popconfirm");
    map.insert("Notification", "@douyinfe/semi-ui/lib/es/notification");
    map.insert("Spin", "@douyinfe/semi-ui/lib/es/spin");
    map.insert("Step", "@douyinfe/semi-ui/lib/es/steps/step");
    map.insert("Upload", "@douyinfe/semi-ui/lib/es/upload");
    map.insert("useFormState", "@douyinfe/semi-ui/lib/es/form");
    map.insert("SideSheet", "@douyinfe/semi-ui/lib/es/sideSheet");
    map.insert("Card", "@douyinfe/semi-ui/lib/es/card");
    map.insert("ToastFactory", "@douyinfe/semi-ui/lib/es/toast");
    map.insert("Form", "@douyinfe/semi-ui/lib/es/form");
    map
}
