/// this file is generated by gen_semi_ui_hashmap.rs
/// do not modify it manually
use crate::semi::SemiImportMap;
use once_cell::sync::Lazy;
pub fn get_semi_ui_map() -> SemiImportMap {
    static SEMI_UI_MAP: Lazy<SemiImportMap> = Lazy::new(|| {
        let json = r#"{
  "IconFont": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFont",
    "isNamedImport": false
  },
  "LocaleProvider": {
    "path": "@douyinfe/semi-ui/lib/es/locale/localeProvider",
    "isNamedImport": false
  },
  "IconChainStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChainStroked",
    "isNamedImport": false
  },
  "IconInfoCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInfoCircle",
    "isNamedImport": false
  },
  "IconH7": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH7",
    "isNamedImport": false
  },
  "IconVideoStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVideoStroked",
    "isNamedImport": false
  },
  "CheckboxGroup": {
    "path": "@douyinfe/semi-ui/lib/es/checkbox/checkboxGroup",
    "isNamedImport": false
  },
  "IconSonicStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSonicStroked",
    "isNamedImport": false
  },
  "IconAppCenter": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAppCenter",
    "isNamedImport": false
  },
  "IconUserCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserCircleStroked",
    "isNamedImport": false
  },
  "IconVoteVideoStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVoteVideoStroked",
    "isNamedImport": false
  },
  "IconH2": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH2",
    "isNamedImport": false
  },
  "IconFilledArrowUp": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFilledArrowUp",
    "isNamedImport": false
  },
  "IconH8": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH8",
    "isNamedImport": false
  },
  "IconTriangleArrow": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTriangleArrow",
    "isNamedImport": false
  },
  "Slider": {
    "path": "@douyinfe/semi-ui/lib/es/slider",
    "isNamedImport": false
  },
  "TreeSelect": {
    "path": "@douyinfe/semi-ui/lib/es/treeSelect",
    "isNamedImport": false
  },
  "Descriptions": {
    "path": "@douyinfe/semi-ui/lib/es/descriptions",
    "isNamedImport": false
  },
  "IconPhone": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPhone",
    "isNamedImport": false
  },
  "IconLoopTextStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLoopTextStroked",
    "isNamedImport": false
  },
  "IconQingyan": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconQingyan",
    "isNamedImport": false
  },
  "IconMusicNoteStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMusicNoteStroked",
    "isNamedImport": false
  },
  "IconCodeStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCodeStroked",
    "isNamedImport": false
  },
  "IconAlignBottom": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignBottom",
    "isNamedImport": false
  },
  "IconCustomerSupport": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCustomerSupport",
    "isNamedImport": false
  },
  "Image": {
    "path": "@douyinfe/semi-ui/lib/es/image",
    "isNamedImport": false
  },
  "IconAlignHRightStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignHRightStroked",
    "isNamedImport": false
  },
  "IconRedo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRedo",
    "isNamedImport": false
  },
  "IconTiktokLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTiktokLogo",
    "isNamedImport": false
  },
  "LocaleConsumer": {
    "path": "@douyinfe/semi-ui/lib/es/locale/localeConsumer",
    "isNamedImport": false
  },
  "IconBookmarkAddStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBookmarkAddStroked",
    "isNamedImport": false
  },
  "IconGallery": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGallery",
    "isNamedImport": false
  },
  "IconInnerSectionStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInnerSectionStroked",
    "isNamedImport": false
  },
  "IconChevronRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChevronRight",
    "isNamedImport": false
  },
  "IconFemale": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFemale",
    "isNamedImport": false
  },
  "IconTriangleUp": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTriangleUp",
    "isNamedImport": false
  },
  "IconAlignVCenterStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignVCenterStroked",
    "isNamedImport": false
  },
  "Icon": {
    "path": "@douyinfe/semi-icons/lib/es/components/Icon",
    "isNamedImport": false
  },
  "IconBackward": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBackward",
    "isNamedImport": false
  },
  "IconLanguage": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLanguage",
    "isNamedImport": false
  },
  "IconStoryStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconStoryStroked",
    "isNamedImport": false
  },
  "IconLikeThumb": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLikeThumb",
    "isNamedImport": false
  },
  "DropdownMenu": {
    "path": "@douyinfe/semi-ui/lib/es/dropdown/dropdownMenu",
    "isNamedImport": false
  },
  "IconCloud": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCloud",
    "isNamedImport": false
  },
  "Tree": {
    "path": "@douyinfe/semi-ui/lib/es/tree",
    "isNamedImport": false
  },
  "IconCheckboxTick": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCheckboxTick",
    "isNamedImport": false
  },
  "IconCopyStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCopyStroked",
    "isNamedImport": false
  },
  "IconTwitter": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTwitter",
    "isNamedImport": false
  },
  "IconBold": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBold",
    "isNamedImport": false
  },
  "IconClose": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconClose",
    "isNamedImport": false
  },
  "IconPlay": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPlay",
    "isNamedImport": false
  },
  "IconCopyAdd": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCopyAdd",
    "isNamedImport": false
  },
  "SideSheet": {
    "path": "@douyinfe/semi-ui/lib/es/sideSheet",
    "isNamedImport": false
  },
  "Typography": {
    "path": "@douyinfe/semi-ui/lib/es/typography",
    "isNamedImport": false
  },
  "IconBytedanceLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBytedanceLogo",
    "isNamedImport": false
  },
  "IconGit": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGit",
    "isNamedImport": false
  },
  "IconShield": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShield",
    "isNamedImport": false
  },
  "Progress": {
    "path": "@douyinfe/semi-ui/lib/es/progress",
    "isNamedImport": false
  },
  "IconCode": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCode",
    "isNamedImport": false
  },
  "IconQuote": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconQuote",
    "isNamedImport": false
  },
  "IconCalendarClock": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCalendarClock",
    "isNamedImport": false
  },
  "IconRankingCardStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRankingCardStroked",
    "isNamedImport": false
  },
  "IconShareMoneyStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShareMoneyStroked",
    "isNamedImport": false
  },
  "IconDuration": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDuration",
    "isNamedImport": false
  },
  "Nav": {
    "path": "@douyinfe/semi-ui/lib/es/navigation",
    "isNamedImport": false
  },
  "IconPiechartH5Stroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPiechartH5Stroked",
    "isNamedImport": false
  },
  "IconIndenpentCornersStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconIndenpentCornersStroked",
    "isNamedImport": false
  },
  "IconAlignVBotStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignVBotStroked",
    "isNamedImport": false
  },
  "IconH5": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH5",
    "isNamedImport": false
  },
  "IconQrCode": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconQrCode",
    "isNamedImport": false
  },
  "IconLightningStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLightningStroked",
    "isNamedImport": false
  },
  "IconHash": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHash",
    "isNamedImport": false
  },
  "IconStarStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconStarStroked",
    "isNamedImport": false
  },
  "IconTickCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTickCircle",
    "isNamedImport": false
  },
  "Radio": {
    "path": "@douyinfe/semi-ui/lib/es/radio",
    "isNamedImport": false
  },
  "IconGridView": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGridView",
    "isNamedImport": false
  },
  "IconIdCard": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconIdCard",
    "isNamedImport": false
  },
  "IconInstagram": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInstagram",
    "isNamedImport": false
  },
  "IconCaretdown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCaretdown",
    "isNamedImport": false
  },
  "Banner": {
    "path": "@douyinfe/semi-ui/lib/es/banner",
    "isNamedImport": false
  },
  "IconFastFoward": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFastFoward",
    "isNamedImport": false
  },
  "IconBookOpenStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBookOpenStroked",
    "isNamedImport": false
  },
  "IconH1": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH1",
    "isNamedImport": false
  },
  "Popover": {
    "path": "@douyinfe/semi-ui/lib/es/popover",
    "isNamedImport": false
  },
  "IconIndependentCornersStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconIndependentCornersStroked",
    "isNamedImport": false
  },
  "IconVolumnSilent": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVolumnSilent",
    "isNamedImport": false
  },
  "IconFilpVertical": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFilpVertical",
    "isNamedImport": false
  },
  "IconPaperclip": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPaperclip",
    "isNamedImport": false
  },
  "IconEyeOpened": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconEyeOpened",
    "isNamedImport": false
  },
  "IconChevronUp": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChevronUp",
    "isNamedImport": false
  },
  "IconBell": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBell",
    "isNamedImport": false
  },
  "IconChevronRightStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChevronRightStroked",
    "isNamedImport": false
  },
  "IconPause": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPause",
    "isNamedImport": false
  },
  "IconDoubleChevronLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDoubleChevronLeft",
    "isNamedImport": false
  },
  "withFormState": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "IconBellStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBellStroked",
    "isNamedImport": false
  },
  "IconDownload": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDownload",
    "isNamedImport": false
  },
  "AvatarGroup": {
    "path": "@douyinfe/semi-ui/lib/es/avatar/avatarGroup",
    "isNamedImport": false
  },
  "OverflowList": {
    "path": "@douyinfe/semi-ui/lib/es/overflowList",
    "isNamedImport": false
  },
  "IconIndentRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconIndentRight",
    "isNamedImport": false
  },
  "IconTopbuzzLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTopbuzzLogo",
    "isNamedImport": false
  },
  "IconVigoLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVigoLogo",
    "isNamedImport": false
  },
  "IconText": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconText",
    "isNamedImport": false
  },
  "IconResso": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconResso",
    "isNamedImport": false
  },
  "IconVersionStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVersionStroked",
    "isNamedImport": false
  },
  "IconIdentity": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconIdentity",
    "isNamedImport": false
  },
  "IconGlobeStroke": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGlobeStroke",
    "isNamedImport": false
  },
  "IconBookmark": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBookmark",
    "isNamedImport": false
  },
  "IconFillStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFillStroked",
    "isNamedImport": false
  },
  "IconCalendar": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCalendar",
    "isNamedImport": false
  },
  "IconCoinMoneyStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCoinMoneyStroked",
    "isNamedImport": false
  },
  "IconEmoji": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconEmoji",
    "isNamedImport": false
  },
  "IconWholeWord": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconWholeWord",
    "isNamedImport": false
  },
  "IconSidebar": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSidebar",
    "isNamedImport": false
  },
  "IconShift": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShift",
    "isNamedImport": false
  },
  "IconBookH5Stroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBookH5Stroked",
    "isNamedImport": false
  },
  "IconRotationStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRotationStroked",
    "isNamedImport": false
  },
  "IconInteractiveStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInteractiveStroked",
    "isNamedImport": false
  },
  "IconGitlabLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGitlabLogo",
    "isNamedImport": false
  },
  "BackTop": {
    "path": "@douyinfe/semi-ui/lib/es/backtop",
    "isNamedImport": false
  },
  "IconOrderedListStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconOrderedListStroked",
    "isNamedImport": false
  },
  "AutoComplete": {
    "path": "@douyinfe/semi-ui/lib/es/autoComplete",
    "isNamedImport": false
  },
  "IconItalic": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconItalic",
    "isNamedImport": false
  },
  "IconModalStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconModalStroked",
    "isNamedImport": false
  },
  "IconSortStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSortStroked",
    "isNamedImport": false
  },
  "IconPulse": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPulse",
    "isNamedImport": false
  },
  "IconTabsStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTabsStroked",
    "isNamedImport": false
  },
  "IconSendStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSendStroked",
    "isNamedImport": false
  },
  "Row": {
    "path": "@douyinfe/semi-ui/lib/es/grid",
    "isNamedImport": true
  },
  "IconBriefcase": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBriefcase",
    "isNamedImport": false
  },
  "IconTicketCodeExchangeStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTicketCodeExchangeStroked",
    "isNamedImport": false
  },
  "IconVideoDouyinStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVideoDouyinStroked",
    "isNamedImport": false
  },
  "IconMonitorStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMonitorStroked",
    "isNamedImport": false
  },
  "IconVideo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVideo",
    "isNamedImport": false
  },
  "IconToutiaoLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconToutiaoLogo",
    "isNamedImport": false
  },
  "IconVoteStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVoteStroked",
    "isNamedImport": false
  },
  "IconMarginStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMarginStroked",
    "isNamedImport": false
  },
  "IconCandlestickChartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCandlestickChartStroked",
    "isNamedImport": false
  },
  "IconFilledArrowDown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFilledArrowDown",
    "isNamedImport": false
  },
  "IconSmallTriangleDown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSmallTriangleDown",
    "isNamedImport": false
  },
  "IconCornerRadiusStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCornerRadiusStroked",
    "isNamedImport": false
  },
  "IconMailStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMailStroked",
    "isNamedImport": false
  },
  "IconNoteMoneyStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconNoteMoneyStroked",
    "isNamedImport": false
  },
  "IconInheritStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInheritStroked",
    "isNamedImport": false
  },
  "IconYoutube": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconYoutube",
    "isNamedImport": false
  },
  "IconScissors": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconScissors",
    "isNamedImport": false
  },
  "IconKanban": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconKanban",
    "isNamedImport": false
  },
  "IconFullScreenStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFullScreenStroked",
    "isNamedImport": false
  },
  "IconFavoriteList": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFavoriteList",
    "isNamedImport": false
  },
  "IconFeishuLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFeishuLogo",
    "isNamedImport": false
  },
  "IconDescend2": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDescend2",
    "isNamedImport": false
  },
  "IconImageStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconImageStroked",
    "isNamedImport": false
  },
  "IconFolder": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFolder",
    "isNamedImport": false
  },
  "IconChevronDown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChevronDown",
    "isNamedImport": false
  },
  "IconChevronLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChevronLeft",
    "isNamedImport": false
  },
  "IconDongchediLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDongchediLogo",
    "isNamedImport": false
  },
  "IconCreditCard": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCreditCard",
    "isNamedImport": false
  },
  "IconIndentLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconIndentLeft",
    "isNamedImport": false
  },
  "IconMailStroked1": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMailStroked1",
    "isNamedImport": false
  },
  "IconDescend": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDescend",
    "isNamedImport": false
  },
  "IconActivity": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconActivity",
    "isNamedImport": false
  },
  "IconButton": {
    "path": "@douyinfe/semi-ui/lib/es/iconButton",
    "isNamedImport": false
  },
  "Tag": {
    "path": "@douyinfe/semi-ui/lib/es/tag",
    "isNamedImport": false
  },
  "TabPane": {
    "path": "@douyinfe/semi-ui/lib/es/tabs/TabPane",
    "isNamedImport": false
  },
  "IconMember": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMember",
    "isNamedImport": false
  },
  "IconSafe": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSafe",
    "isNamedImport": false
  },
  "IconGiftStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGiftStroked",
    "isNamedImport": false
  },
  "IconLeftCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLeftCircleStroked",
    "isNamedImport": false
  },
  "IconReply": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconReply",
    "isNamedImport": false
  },
  "IconShrink": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShrink",
    "isNamedImport": false
  },
  "IconUserListStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserListStroked",
    "isNamedImport": false
  },
  "IconComponent": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconComponent",
    "isNamedImport": false
  },
  "IconEditStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconEditStroked",
    "isNamedImport": false
  },
  "IconPipixiaLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPipixiaLogo",
    "isNamedImport": false
  },
  "TimePicker": {
    "path": "@douyinfe/semi-ui/lib/es/timePicker",
    "isNamedImport": false
  },
  "IconHelm": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHelm",
    "isNamedImport": false
  },
  "Avatar": {
    "path": "@douyinfe/semi-ui/lib/es/avatar",
    "isNamedImport": false
  },
  "IconVideoUrlStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVideoUrlStroked",
    "isNamedImport": false
  },
  "IconAlignCenterVertical": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignCenterVertical",
    "isNamedImport": false
  },
  "Switch": {
    "path": "@douyinfe/semi-ui/lib/es/switch",
    "isNamedImport": false
  },
  "IconCart": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCart",
    "isNamedImport": false
  },
  "IconLayers": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLayers",
    "isNamedImport": false
  },
  "Notification": {
    "path": "@douyinfe/semi-ui/lib/es/notification",
    "isNamedImport": false
  },
  "Collapse": {
    "path": "@douyinfe/semi-ui/lib/es/collapse",
    "isNamedImport": false
  },
  "Empty": {
    "path": "@douyinfe/semi-ui/lib/es/empty",
    "isNamedImport": false
  },
  "IconPriceTag": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPriceTag",
    "isNamedImport": false
  },
  "IconCaseSensitive": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCaseSensitive",
    "isNamedImport": false
  },
  "IconPieChart2Stroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPieChart2Stroked",
    "isNamedImport": false
  },
  "IconEyeClosedSolid": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconEyeClosedSolid",
    "isNamedImport": false
  },
  "Pagination": {
    "path": "@douyinfe/semi-ui/lib/es/pagination",
    "isNamedImport": false
  },
  "IconIssueStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconIssueStroked",
    "isNamedImport": false
  },
  "IconLikeHeart": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLikeHeart",
    "isNamedImport": false
  },
  "IconSaveStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSaveStroked",
    "isNamedImport": false
  },
  "IconUserCardPhone": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserCardPhone",
    "isNamedImport": false
  },
  "IconMenu": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMenu",
    "isNamedImport": false
  },
  "IconCenterRightStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCenterRightStroked",
    "isNamedImport": false
  },
  "IconTransparentStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTransparentStroked",
    "isNamedImport": false
  },
  "ConfigProvider": {
    "path": "@douyinfe/semi-ui/lib/es/configProvider",
    "isNamedImport": false
  },
  "IconPlus": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPlus",
    "isNamedImport": false
  },
  "IconSettingStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSettingStroked",
    "isNamedImport": false
  },
  "IconSmallTriangleTop": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSmallTriangleTop",
    "isNamedImport": false
  },
  "Form": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "useFieldState": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "IconSearch": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSearch",
    "isNamedImport": false
  },
  "IconEyeClosed": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconEyeClosed",
    "isNamedImport": false
  },
  "IconXiguaLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconXiguaLogo",
    "isNamedImport": false
  },
  "IconApartment": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconApartment",
    "isNamedImport": false
  },
  "IconForward": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconForward",
    "isNamedImport": false
  },
  "IconFastForward": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFastForward",
    "isNamedImport": false
  },
  "IconMark": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMark",
    "isNamedImport": false
  },
  "IconTabArrowStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTabArrowStroked",
    "isNamedImport": false
  },
  "IconTvCheckedStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTvCheckedStroked",
    "isNamedImport": false
  },
  "IconCarouselStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCarouselStroked",
    "isNamedImport": false
  },
  "IconArticle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArticle",
    "isNamedImport": false
  },
  "withField": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "Anchor": {
    "path": "@douyinfe/semi-ui/lib/es/anchor",
    "isNamedImport": false
  },
  "IconFaceuLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFaceuLogo",
    "isNamedImport": false
  },
  "IconPrint": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPrint",
    "isNamedImport": false
  },
  "IconPercentage": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPercentage",
    "isNamedImport": false
  },
  "IconSmallTriangleRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSmallTriangleRight",
    "isNamedImport": false
  },
  "IconLineChartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLineChartStroked",
    "isNamedImport": false
  },
  "IconStop": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconStop",
    "isNamedImport": false
  },
  "IconBarChartHStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBarChartHStroked",
    "isNamedImport": false
  },
  "IconJianying": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconJianying",
    "isNamedImport": false
  },
  "IconRefresh": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRefresh",
    "isNamedImport": false
  },
  "IconHandle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHandle",
    "isNamedImport": false
  },
  "IconOrderedList": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconOrderedList",
    "isNamedImport": false
  },
  "IconPhoneStroke": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPhoneStroke",
    "isNamedImport": false
  },
  "IconChevronUpDown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChevronUpDown",
    "isNamedImport": false
  },
  "IconTriangleArrowVertical": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTriangleArrowVertical",
    "isNamedImport": false
  },
  "IconArrowDown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowDown",
    "isNamedImport": false
  },
  "IconTemplateStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTemplateStroked",
    "isNamedImport": false
  },
  "IconMail": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMail",
    "isNamedImport": false
  },
  "useFormState": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "IconStrikeThrough": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconStrikeThrough",
    "isNamedImport": false
  },
  "IconUploadError": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUploadError",
    "isNamedImport": false
  },
  "IconUserCardVideo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserCardVideo",
    "isNamedImport": false
  },
  "IconCrop": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCrop",
    "isNamedImport": false
  },
  "IconFontColor": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFontColor",
    "isNamedImport": false
  },
  "IconPlusCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPlusCircle",
    "isNamedImport": false
  },
  "IconH6": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH6",
    "isNamedImport": false
  },
  "IconCheckCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCheckCircleStroked",
    "isNamedImport": false
  },
  "TagInput": {
    "path": "@douyinfe/semi-ui/lib/es/tagInput",
    "isNamedImport": false
  },
  "Step": {
    "path": "@douyinfe/semi-ui/lib/es/steps/step",
    "isNamedImport": false
  },
  "IconHistogram": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHistogram",
    "isNamedImport": false
  },
  "IconShareStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShareStroked",
    "isNamedImport": false
  },
  "IconRefresh2": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRefresh2",
    "isNamedImport": false
  },
  "IconBolt": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBolt",
    "isNamedImport": false
  },
  "IconComponentStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconComponentStroked",
    "isNamedImport": false
  },
  "IconGithubLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGithubLogo",
    "isNamedImport": false
  },
  "IconFolderStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFolderStroked",
    "isNamedImport": false
  },
  "IconDivide": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDivide",
    "isNamedImport": false
  },
  "IconUnlock": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUnlock",
    "isNamedImport": false
  },
  "IconShrinkScreenStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShrinkScreenStroked",
    "isNamedImport": false
  },
  "IconArrowDownRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowDownRight",
    "isNamedImport": false
  },
  "IconSectionStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSectionStroked",
    "isNamedImport": false
  },
  "IconCrown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCrown",
    "isNamedImport": false
  },
  "IconCamera": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCamera",
    "isNamedImport": false
  },
  "IconGridRectangle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGridRectangle",
    "isNamedImport": false
  },
  "IconReplyStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconReplyStroked",
    "isNamedImport": false
  },
  "IconPlayCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPlayCircle",
    "isNamedImport": false
  },
  "useFormApi": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "Spin": {
    "path": "@douyinfe/semi-ui/lib/es/spin",
    "isNamedImport": false
  },
  "IconSearchStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSearchStroked",
    "isNamedImport": false
  },
  "IconConnectionPoint1": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconConnectionPoint1",
    "isNamedImport": false
  },
  "IconAlarm": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlarm",
    "isNamedImport": false
  },
  "IconTreeTriangleRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTreeTriangleRight",
    "isNamedImport": false
  },
  "IconH3": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH3",
    "isNamedImport": false
  },
  "Button": {
    "path": "@douyinfe/semi-ui/lib/es/button",
    "isNamedImport": false
  },
  "IconArrowUp": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowUp",
    "isNamedImport": false
  },
  "IconAlignRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignRight",
    "isNamedImport": false
  },
  "IconListView": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconListView",
    "isNamedImport": false
  },
  "IconTerminal": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTerminal",
    "isNamedImport": false
  },
  "IconThumbUpStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconThumbUpStroked",
    "isNamedImport": false
  },
  "IconTicketCodeStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTicketCodeStroked",
    "isNamedImport": false
  },
  "IconH4": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH4",
    "isNamedImport": false
  },
  "IconAlignVBottomStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignVBottomStroked",
    "isNamedImport": false
  },
  "IconFixedStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFixedStroked",
    "isNamedImport": false
  },
  "IconFingerLeftStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFingerLeftStroked",
    "isNamedImport": false
  },
  "IconMinusCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMinusCircle",
    "isNamedImport": false
  },
  "IconAscend": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAscend",
    "isNamedImport": false
  },
  "ArrayField": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "IconDisc": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDisc",
    "isNamedImport": false
  },
  "IconGridSquare": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGridSquare",
    "isNamedImport": false
  },
  "IconHn": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHn",
    "isNamedImport": false
  },
  "IconShieldStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShieldStroked",
    "isNamedImport": false
  },
  "IconDownCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDownCircleStroked",
    "isNamedImport": false
  },
  "IconCloudUploadStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCloudUploadStroked",
    "isNamedImport": false
  },
  "IconTemplate": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTemplate",
    "isNamedImport": false
  },
  "IconUpload": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUpload",
    "isNamedImport": false
  },
  "IconVideoListStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVideoListStroked",
    "isNamedImport": false
  },
  "IconRoute": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRoute",
    "isNamedImport": false
  },
  "convertIcon": {
    "path": "@douyinfe/semi-icons/lib/es/components/Icon",
    "isNamedImport": false
  },
  "InputGroup": {
    "path": "@douyinfe/semi-ui/lib/es/input/inputGroup",
    "isNamedImport": false
  },
  "SubNav": {
    "path": "@douyinfe/semi-ui/lib/es/navigation/SubNav",
    "isNamedImport": false
  },
  "IconAlignHLeftStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignHLeftStroked",
    "isNamedImport": false
  },
  "IconInbox": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInbox",
    "isNamedImport": false
  },
  "IconStopwatchStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconStopwatchStroked",
    "isNamedImport": false
  },
  "IconDownloadStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDownloadStroked",
    "isNamedImport": false
  },
  "IconFolderOpen": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFolderOpen",
    "isNamedImport": false
  },
  "IconSync": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSync",
    "isNamedImport": false
  },
  "IconQuit": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconQuit",
    "isNamedImport": false
  },
  "IconSong": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSong",
    "isNamedImport": false
  },
  "IconUndo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUndo",
    "isNamedImport": false
  },
  "IconSmartphoneStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSmartphoneStroked",
    "isNamedImport": false
  },
  "IconWifi": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconWifi",
    "isNamedImport": false
  },
  "TagGroup": {
    "path": "@douyinfe/semi-ui/lib/es/tag/group",
    "isNamedImport": false
  },
  "IconHelpCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHelpCircleStroked",
    "isNamedImport": false
  },
  "Layout": {
    "path": "@douyinfe/semi-ui/lib/es/layout",
    "isNamedImport": true
  },
  "IconMinusStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMinusStroked",
    "isNamedImport": false
  },
  "IconSave": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSave",
    "isNamedImport": false
  },
  "IconMicrophoneOff": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMicrophoneOff",
    "isNamedImport": false
  },
  "IconImage": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconImage",
    "isNamedImport": false
  },
  "IconBookmarkDeleteStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBookmarkDeleteStroked",
    "isNamedImport": false
  },
  "IconConfigStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconConfigStroked",
    "isNamedImport": false
  },
  "IconRingChartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRingChartStroked",
    "isNamedImport": false
  },
  "Breadcrumb": {
    "path": "@douyinfe/semi-ui/lib/es/breadcrumb",
    "isNamedImport": false
  },
  "IconUserSetting": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserSetting",
    "isNamedImport": false
  },
  "IconFacebook": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFacebook",
    "isNamedImport": false
  },
  "IconGridStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGridStroked",
    "isNamedImport": false
  },
  "IconTick": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTick",
    "isNamedImport": false
  },
  "TextArea": {
    "path": "@douyinfe/semi-ui/lib/es/input/textarea",
    "isNamedImport": false
  },
  "IconArrowDownLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowDownLeft",
    "isNamedImport": false
  },
  "IconRadio": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRadio",
    "isNamedImport": false
  },
  "IconMinus": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMinus",
    "isNamedImport": false
  },
  "IconSimilarity": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSimilarity",
    "isNamedImport": false
  },
  "Input": {
    "path": "@douyinfe/semi-ui/lib/es/input",
    "isNamedImport": false
  },
  "IconMute": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMute",
    "isNamedImport": false
  },
  "IconCheckChoiceStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCheckChoiceStroked",
    "isNamedImport": false
  },
  "IconServerStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconServerStroked",
    "isNamedImport": false
  },
  "IconEdit": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconEdit",
    "isNamedImport": false
  },
  "IconCrossCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCrossCircleStroked",
    "isNamedImport": false
  },
  "Select": {
    "path": "@douyinfe/semi-ui/lib/es/select",
    "isNamedImport": false
  },
  "IconFollowStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFollowStroked",
    "isNamedImport": false
  },
  "IconHeartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHeartStroked",
    "isNamedImport": false
  },
  "IconRowsStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRowsStroked",
    "isNamedImport": false
  },
  "IconUnlink": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUnlink",
    "isNamedImport": false
  },
  "IconUserStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserStroked",
    "isNamedImport": false
  },
  "IconBarChartVStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBarChartVStroked",
    "isNamedImport": false
  },
  "IconRestart": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRestart",
    "isNamedImport": false
  },
  "IconWeibo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconWeibo",
    "isNamedImport": false
  },
  "IconFigma": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFigma",
    "isNamedImport": false
  },
  "Tooltip": {
    "path": "@douyinfe/semi-ui/lib/es/tooltip",
    "isNamedImport": false
  },
  "IconOption": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconOption",
    "isNamedImport": false
  },
  "IconSignal": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSignal",
    "isNamedImport": false
  },
  "IconBottomRightStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBottomRightStroked",
    "isNamedImport": false
  },
  "IconTopLeftStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTopLeftStroked",
    "isNamedImport": false
  },
  "IconVolume2": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVolume2",
    "isNamedImport": false
  },
  "IconExternalOpenStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconExternalOpenStroked",
    "isNamedImport": false
  },
  "IconTaskMoneyStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTaskMoneyStroked",
    "isNamedImport": false
  },
  "IconFile": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFile",
    "isNamedImport": false
  },
  "ScrollItem": {
    "path": "@douyinfe/semi-ui/lib/es/scrollList/scrollItem",
    "isNamedImport": false
  },
  "IconPlusCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPlusCircleStroked",
    "isNamedImport": false
  },
  "IconSemiLogo": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSemiLogo",
    "isNamedImport": false
  },
  "IconAlertCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlertCircle",
    "isNamedImport": false
  },
  "IconPrizeStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPrizeStroked",
    "isNamedImport": false
  },
  "IconTopCenterStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTopCenterStroked",
    "isNamedImport": false
  },
  "IconMicrophone": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMicrophone",
    "isNamedImport": false
  },
  "IconElementStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconElementStroked",
    "isNamedImport": false
  },
  "Skeleton": {
    "path": "@douyinfe/semi-ui/lib/es/skeleton",
    "isNamedImport": false
  },
  "IconAlignVTopStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignVTopStroked",
    "isNamedImport": false
  },
  "IconCaretup": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCaretup",
    "isNamedImport": false
  },
  "IconBranch": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBranch",
    "isNamedImport": false
  },
  "IconMoon": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMoon",
    "isNamedImport": false
  },
  "IconImport": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconImport",
    "isNamedImport": false
  },
  "Table": {
    "path": "@douyinfe/semi-ui/lib/es/table",
    "isNamedImport": false
  },
  "Collapsible": {
    "path": "@douyinfe/semi-ui/lib/es/collapsible",
    "isNamedImport": false
  },
  "Space": {
    "path": "@douyinfe/semi-ui/lib/es/space",
    "isNamedImport": false
  },
  "IconSmallTriangleLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSmallTriangleLeft",
    "isNamedImport": false
  },
  "IconBookStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBookStroked",
    "isNamedImport": false
  },
  "IconKeyStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconKeyStroked",
    "isNamedImport": false
  },
  "IconSendMsgStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSendMsgStroked",
    "isNamedImport": false
  },
  "IconMoneyExchangeStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMoneyExchangeStroked",
    "isNamedImport": false
  },
  "IconLink": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLink",
    "isNamedImport": false
  },
  "IconDoubleChevronRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDoubleChevronRight",
    "isNamedImport": false
  },
  "Upload": {
    "path": "@douyinfe/semi-ui/lib/es/upload",
    "isNamedImport": false
  },
  "IconMore": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMore",
    "isNamedImport": false
  },
  "IconMinimize": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMinimize",
    "isNamedImport": false
  },
  "InputNumber": {
    "path": "@douyinfe/semi-ui/lib/es/inputNumber",
    "isNamedImport": false
  },
  "Tabs": {
    "path": "@douyinfe/semi-ui/lib/es/tabs",
    "isNamedImport": false
  },
  "CardGroup": {
    "path": "@douyinfe/semi-ui/lib/es/card/cardGroup",
    "isNamedImport": false
  },
  "ScrollList": {
    "path": "@douyinfe/semi-ui/lib/es/scrollList",
    "isNamedImport": false
  },
  "IconDelete": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDelete",
    "isNamedImport": false
  },
  "IconHistory": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHistory",
    "isNamedImport": false
  },
  "IconRegExp": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRegExp",
    "isNamedImport": false
  },
  "IconDeleteStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDeleteStroked",
    "isNamedImport": false
  },
  "IconTreeTriangleDown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTreeTriangleDown",
    "isNamedImport": false
  },
  "IconUnlockStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUnlockStroked",
    "isNamedImport": false
  },
  "IconCloudStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCloudStroked",
    "isNamedImport": false
  },
  "IconVolume1": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVolume1",
    "isNamedImport": false
  },
  "IconTriangleDown": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTriangleDown",
    "isNamedImport": false
  },
  "IconExternalOpen": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconExternalOpen",
    "isNamedImport": false
  },
  "IconRedoStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRedoStroked",
    "isNamedImport": false
  },
  "useFieldApi": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "IconTop": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTop",
    "isNamedImport": false
  },
  "Highlight": {
    "path": "@douyinfe/semi-ui/lib/es/highlight",
    "isNamedImport": false
  },
  "Dropdown": {
    "path": "@douyinfe/semi-ui/lib/es/dropdown",
    "isNamedImport": false
  },
  "IconArchive": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArchive",
    "isNamedImport": false
  },
  "Col": {
    "path": "@douyinfe/semi-ui/lib/es/grid",
    "isNamedImport": true
  },
  "IconClear": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconClear",
    "isNamedImport": false
  },
  "IconSend": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSend",
    "isNamedImport": false
  },
  "IconAlignHCenterStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignHCenterStroked",
    "isNamedImport": false
  },
  "ImagePreview": {
    "path": "@douyinfe/semi-ui/lib/es/image",
    "isNamedImport": false
  },
  "Steps": {
    "path": "@douyinfe/semi-ui/lib/es/steps",
    "isNamedImport": false
  },
  "IconLoading": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLoading",
    "isNamedImport": false
  },
  "IconApps": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconApps",
    "isNamedImport": false
  },
  "IconCheckboxIndeterminate": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCheckboxIndeterminate",
    "isNamedImport": false
  },
  "IconHelpCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHelpCircle",
    "isNamedImport": false
  },
  "IconBulb": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBulb",
    "isNamedImport": false
  },
  "IconLive": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLive",
    "isNamedImport": false
  },
  "IconAlignCenter": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignCenter",
    "isNamedImport": false
  },
  "IconSpin": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSpin",
    "isNamedImport": false
  },
  "IconTextStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTextStroked",
    "isNamedImport": false
  },
  "IconHourglassStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHourglassStroked",
    "isNamedImport": false
  },
  "IconGlobe": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGlobe",
    "isNamedImport": false
  },
  "IconExit": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconExit",
    "isNamedImport": false
  },
  "IconMaximize": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMaximize",
    "isNamedImport": false
  },
  "IconScan": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconScan",
    "isNamedImport": false
  },
  "IconGridView1": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGridView1",
    "isNamedImport": false
  },
  "IconPieChartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPieChartStroked",
    "isNamedImport": false
  },
  "IconCommand": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCommand",
    "isNamedImport": false
  },
  "IconSort": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSort",
    "isNamedImport": false
  },
  "IconMapPin": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMapPin",
    "isNamedImport": false
  },
  "IconUserAdd": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserAdd",
    "isNamedImport": false
  },
  "IconBottomLeftStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBottomLeftStroked",
    "isNamedImport": false
  },
  "DropdownItem": {
    "path": "@douyinfe/semi-ui/lib/es/dropdown/dropdownItem",
    "isNamedImport": false
  },
  "IconCenterLeftStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCenterLeftStroked",
    "isNamedImport": false
  },
  "Modal": {
    "path": "@douyinfe/semi-ui/lib/es/modal",
    "isNamedImport": false
  },
  "IconCalendarStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCalendarStroked",
    "isNamedImport": false
  },
  "IconFilter": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFilter",
    "isNamedImport": false
  },
  "IconAlertTriangle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlertTriangle",
    "isNamedImport": false
  },
  "Card": {
    "path": "@douyinfe/semi-ui/lib/es/card",
    "isNamedImport": false
  },
  "IconKey": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconKey",
    "isNamedImport": false
  },
  "IconVennChartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVennChartStroked",
    "isNamedImport": false
  },
  "withFormApi": {
    "path": "@douyinfe/semi-ui/lib/es/form",
    "isNamedImport": true
  },
  "IconStackBarChartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconStackBarChartStroked",
    "isNamedImport": false
  },
  "IconTrueFalseStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTrueFalseStroked",
    "isNamedImport": false
  },
  "IconCustomize": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCustomize",
    "isNamedImport": false
  },
  "Timeline": {
    "path": "@douyinfe/semi-ui/lib/es/timeline",
    "isNamedImport": false
  },
  "IconLineHeight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLineHeight",
    "isNamedImport": false
  },
  "IconAbsoluteStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAbsoluteStroked",
    "isNamedImport": false
  },
  "IconExpand": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconExpand",
    "isNamedImport": false
  },
  "Toast": {
    "path": "@douyinfe/semi-ui/lib/es/toast",
    "isNamedImport": false
  },
  "IconComment": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconComment",
    "isNamedImport": false
  },
  "IconSun": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSun",
    "isNamedImport": false
  },
  "IconCopy": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCopy",
    "isNamedImport": false
  },
  "IconConnectionPoint2": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconConnectionPoint2",
    "isNamedImport": false
  },
  "IconCheckList": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCheckList",
    "isNamedImport": false
  },
  "IconBriefStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBriefStroked",
    "isNamedImport": false
  },
  "IconList": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconList",
    "isNamedImport": false
  },
  "List": {
    "path": "@douyinfe/semi-ui/lib/es/list",
    "isNamedImport": false
  },
  "IconEdit2Stroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconEdit2Stroked",
    "isNamedImport": false
  },
  "IconNineGridStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconNineGridStroked",
    "isNamedImport": false
  },
  "RadioGroup": {
    "path": "@douyinfe/semi-ui/lib/es/radio/radioGroup",
    "isNamedImport": false
  },
  "IconInviteStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInviteStroked",
    "isNamedImport": false
  },
  "Transfer": {
    "path": "@douyinfe/semi-ui/lib/es/transfer",
    "isNamedImport": false
  },
  "IconChevronDownStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChevronDownStroked",
    "isNamedImport": false
  },
  "IconUserGroup": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserGroup",
    "isNamedImport": false
  },
  "Divider": {
    "path": "@douyinfe/semi-ui/lib/es/divider",
    "isNamedImport": false
  },
  "IconAlignLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignLeft",
    "isNamedImport": false
  },
  "IconAlignTop": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignTop",
    "isNamedImport": false
  },
  "IconMinusCircleStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMinusCircleStroked",
    "isNamedImport": false
  },
  "IconUser": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUser",
    "isNamedImport": false
  },
  "IconMapPinStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMapPinStroked",
    "isNamedImport": false
  },
  "IconSetting": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSetting",
    "isNamedImport": false
  },
  "IconVerify": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconVerify",
    "isNamedImport": false
  },
  "IconHome": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHome",
    "isNamedImport": false
  },
  "IconMoreStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMoreStroked",
    "isNamedImport": false
  },
  "IconHourglass": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHourglass",
    "isNamedImport": false
  },
  "Rating": {
    "path": "@douyinfe/semi-ui/lib/es/rating",
    "isNamedImport": false
  },
  "IconH9": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconH9",
    "isNamedImport": false
  },
  "IconWindowAdaptionStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconWindowAdaptionStroked",
    "isNamedImport": false
  },
  "IconServer": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconServer",
    "isNamedImport": false
  },
  "IconFlipHorizontal": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFlipHorizontal",
    "isNamedImport": false
  },
  "IconArrowLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowLeft",
    "isNamedImport": false
  },
  "IconAt": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAt",
    "isNamedImport": false
  },
  "IconArrowUpRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowUpRight",
    "isNamedImport": false
  },
  "IconPlusStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPlusStroked",
    "isNamedImport": false
  },
  "IconFlowChartStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFlowChartStroked",
    "isNamedImport": false
  },
  "IconTextRectangle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTextRectangle",
    "isNamedImport": false
  },
  "IconUserCircle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUserCircle",
    "isNamedImport": false
  },
  "IconContrast": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconContrast",
    "isNamedImport": false
  },
  "IconBackTop": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBackTop",
    "isNamedImport": false
  },
  "IconUnderline": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUnderline",
    "isNamedImport": false
  },
  "ToastFactory": {
    "path": "@douyinfe/semi-ui/lib/es/toast",
    "isNamedImport": true
  },
  "IconMusic": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMusic",
    "isNamedImport": false
  },
  "Popconfirm": {
    "path": "@douyinfe/semi-ui/lib/es/popconfirm",
    "isNamedImport": false
  },
  "IconDislikeThumb": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDislikeThumb",
    "isNamedImport": false
  },
  "IconClock": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconClock",
    "isNamedImport": false
  },
  "IconBrackets": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBrackets",
    "isNamedImport": false
  },
  "IconDesktop": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconDesktop",
    "isNamedImport": false
  },
  "IconAlignJustify": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconAlignJustify",
    "isNamedImport": false
  },
  "IconStar": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconStar",
    "isNamedImport": false
  },
  "NavItem": {
    "path": "@douyinfe/semi-ui/lib/es/navigation/Item",
    "isNamedImport": false
  },
  "IconSmartphoneCheckStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSmartphoneCheckStroked",
    "isNamedImport": false
  },
  "IconCommentStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCommentStroked",
    "isNamedImport": false
  },
  "ButtonGroup": {
    "path": "@douyinfe/semi-ui/lib/es/button/buttonGroup",
    "isNamedImport": false
  },
  "IconCrossStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCrossStroked",
    "isNamedImport": false
  },
  "Carousel": {
    "path": "@douyinfe/semi-ui/lib/es/carousel",
    "isNamedImport": false
  },
  "IconCustomerSupportStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconCustomerSupportStroked",
    "isNamedImport": false
  },
  "IconHomeStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHomeStroked",
    "isNamedImport": false
  },
  "Calendar": {
    "path": "@douyinfe/semi-ui/lib/es/calendar",
    "isNamedImport": false
  },
  "IconLockStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLockStroked",
    "isNamedImport": false
  },
  "IconArrowUpLeft": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowUpLeft",
    "isNamedImport": false
  },
  "IconMarginLeftStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMarginLeftStroked",
    "isNamedImport": false
  },
  "IconExport": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconExport",
    "isNamedImport": false
  },
  "IconBox": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBox",
    "isNamedImport": false
  },
  "IconInherit": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconInherit",
    "isNamedImport": false
  },
  "IconTestScoreStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTestScoreStroked",
    "isNamedImport": false
  },
  "IconChecklistStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconChecklistStroked",
    "isNamedImport": false
  },
  "IconHorn": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconHorn",
    "isNamedImport": false
  },
  "IconComponentPlaceholderStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconComponentPlaceholderStroked",
    "isNamedImport": false
  },
  "IconArrowRight": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconArrowRight",
    "isNamedImport": false
  },
  "IconColumnsStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconColumnsStroked",
    "isNamedImport": false
  },
  "IconGift": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconGift",
    "isNamedImport": false
  },
  "IconMale": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconMale",
    "isNamedImport": false
  },
  "IconButtonStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconButtonStroked",
    "isNamedImport": false
  },
  "IconPuzzle": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconPuzzle",
    "isNamedImport": false
  },
  "IconBottomCenterStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBottomCenterStroked",
    "isNamedImport": false
  },
  "DropdownDivider": {
    "path": "@douyinfe/semi-ui/lib/es/dropdown/dropdownDivider",
    "isNamedImport": false
  },
  "IconForwardStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconForwardStroked",
    "isNamedImport": false
  },
  "SplitButtonGroup": {
    "path": "@douyinfe/semi-ui/lib/es/button/splitButtonGroup",
    "isNamedImport": false
  },
  "IconLock": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconLock",
    "isNamedImport": false
  },
  "Cascader": {
    "path": "@douyinfe/semi-ui/lib/es/cascader",
    "isNamedImport": false
  },
  "Checkbox": {
    "path": "@douyinfe/semi-ui/lib/es/checkbox",
    "isNamedImport": false
  },
  "IconRotate": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRotate",
    "isNamedImport": false
  },
  "IconSourceControl": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconSourceControl",
    "isNamedImport": false
  },
  "IconTopRightStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTopRightStroked",
    "isNamedImport": false
  },
  "IconBeaker": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconBeaker",
    "isNamedImport": false
  },
  "DatePicker": {
    "path": "@douyinfe/semi-ui/lib/es/datePicker",
    "isNamedImport": false
  },
  "IconRealSizeStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconRealSizeStroked",
    "isNamedImport": false
  },
  "IconUnChainStroked": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconUnChainStroked",
    "isNamedImport": false
  },
  "IconShoppingBag": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconShoppingBag",
    "isNamedImport": false
  },
  "IconFlag": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconFlag",
    "isNamedImport": false
  },
  "Badge": {
    "path": "@douyinfe/semi-ui/lib/es/badge",
    "isNamedImport": false
  },
  "IconColorPalette": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconColorPalette",
    "isNamedImport": false
  },
  "IconWrench": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconWrench",
    "isNamedImport": false
  },
  "IconTypograph": {
    "path": "@douyinfe/semi-icons/lib/es/icons/IconTypograph",
    "isNamedImport": false
  }
}"#;
        serde_json::from_str(json).unwrap()
    });
    SEMI_UI_MAP.clone()
}
