// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Add a new pet to the store
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/addPet
 */
export const petPostApi = new RequestBuilder<petPostApi.Req, petPostApi.Res>({
  url: "/pet",
  method: "post",
});

export namespace petPostApi {
  export interface Req {}

  export type Res = any;
}
