// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Update an existing pet
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/updatePet
 */
export const petPutApi = new RequestBuilder<petPutApi.Req, petPutApi.Res>({
  url: "/pet",
  method: "put",
});

export namespace petPutApi {
  export interface Req {}

  export type Res = any;
}
