// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Returns pet inventories by status
 * @tags store
 * @see http://localhost:3000/swagger#/store/getInventory
 */
export const storeInventoryGetApi = new RequestBuilder<
  storeInventoryGetApi.Req,
  storeInventoryGetApi.Res
>({
  url: "/store/inventory",
  method: "get",
});

export namespace storeInventoryGetApi {
  export interface Req {}

  export type Res = any;
}
