// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Logs out current logged in user session
 * @tags user
 * @see http://localhost:3000/swagger#/user/logoutUser
 */
export const userLogoutGetApi = new RequestBuilder<
  userLogoutGetApi.Req,
  userLogoutGetApi.Res
>({
  url: "/user/logout",
  method: "get",
});

export namespace userLogoutGetApi {
  export interface Req {}

  export type Res = any;
}
