// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * uploads an image
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/uploadFile
 */
export const petPetIdUploadImagePostApi = new RequestBuilder<
  petPetIdUploadImagePostApi.Req,
  petPetIdUploadImagePostApi.Res
>({
  url: "/pet/{petId}/uploadImage",
  method: "post",
  urlPathParams: ["petId"],
});

export namespace petPetIdUploadImagePostApi {
  export interface Req {}

  export type Res = any;
}
