// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Creates list of users with given input array
 * @tags user
 * @see http://localhost:3000/swagger#/user/createUsersWithArrayInput
 */
export const userCreateWithArrayPostApi = new RequestBuilder<
  userCreateWithArrayPostApi.Req,
  userCreateWithArrayPostApi.Res
>({
  url: "/user/createWithArray",
  method: "post",
});

export namespace userCreateWithArrayPostApi {
  export interface Req {}

  export type Res = any;
}
