// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Finds Pets by status
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/findPetsByStatus
 */
export const petFindByStatusGetApi = new RequestBuilder<
  petFindByStatusGetApi.Req,
  petFindByStatusGetApi.Res
>({
  url: "/pet/findByStatus",
  method: "get",
});

export namespace petFindByStatusGetApi {
  export interface Req {}

  export type Res = any;
}
