// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Deletes a pet
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/deletePet
 */
export const petPetIdDeleteApi = new RequestBuilder<
  petPetIdDeleteApi.Req,
  petPetIdDeleteApi.Res
>({
  url: "/pet/{petId}",
  method: "delete",
  urlPathParams: ["petId"],
});

export namespace petPetIdDeleteApi {
  export interface Req {}

  export type Res = any;
}
