// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Find pet by ID
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/getPetById
 */
export const petPetIdGetApi = new RequestBuilder<
  petPetIdGetApi.Req,
  petPetIdGetApi.Res
>({
  url: "/pet/{petId}",
  method: "get",
  urlPathParams: ["petId"],
});

export namespace petPetIdGetApi {
  export interface Req {}

  export type Res = any;
}
