// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Updates a pet in the store with form data
 * @tags pet
 * @see http://localhost:3000/swagger#/pet/updatePetWithForm
 */
export const petPetIdPostApi = new RequestBuilder<
  petPetIdPostApi.Req,
  petPetIdPostApi.Res
>({
  url: "/pet/{petId}",
  method: "post",
  urlPathParams: ["petId"],
});

export namespace petPetIdPostApi {
  export interface Req {}

  export type Res = any;
}
