// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Logs user into the system
 * @tags user
 * @see http://localhost:3000/swagger#/user/loginUser
 */
export const userLoginGetApi = new RequestBuilder<
  userLoginGetApi.Req,
  userLoginGetApi.Res
>({
  url: "/user/login",
  method: "get",
});

export namespace userLoginGetApi {
  export interface Req {}

  export type Res = any;
}
