// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Delete user
 * @tags user
 * @see http://localhost:3000/swagger#/user/deleteUser
 */
export const userUsernameDeleteApi = new RequestBuilder<
  userUsernameDeleteApi.Req,
  userUsernameDeleteApi.Res
>({
  url: "/user/{username}",
  method: "delete",
  urlPathParams: ["username"],
});

export namespace userUsernameDeleteApi {
  export interface Req {}

  export type Res = any;
}
