// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Get user by user name
 * @tags user
 * @see http://localhost:3000/swagger#/user/getUserByName
 */
export const userUsernameGetApi = new RequestBuilder<
  userUsernameGetApi.Req,
  userUsernameGetApi.Res
>({
  url: "/user/{username}",
  method: "get",
  urlPathParams: ["username"],
});

export namespace userUsernameGetApi {
  export interface Req {}

  export type Res = any;
}
