// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Updated user
 * @tags user
 * @see http://localhost:3000/swagger#/user/updateUser
 */
export const userUsernamePutApi = new RequestBuilder<
  userUsernamePutApi.Req,
  userUsernamePutApi.Res
>({
  url: "/user/{username}",
  method: "put",
  urlPathParams: ["username"],
});

export namespace userUsernamePutApi {
  export interface Req {}

  export type Res = any;
}
