[package]
name = "s_swc_visitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_core = { version = "0.27", features = ["ecma_quote", "ecma_utils"] }
tracing = "0.1.32"