// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Place an order for a pet
 * @tags store
 * @see http://localhost:3000/swagger#/store/placeOrder
 */
export const storeOrderPostApi = new RequestBuilder<
  storeOrderPostApi.Req,
  storeOrderPostApi.Res
>({
  url: "/store/order",
  method: "post",
});

export namespace storeOrderPostApi {
  export interface Req {}

  export type Res = any;
}
