// do not edit this file manually, it will be overwritten by @dune2/cli
import { RequestBuilder } from "@dune2/tools/rq";
/**
 * Creates list of users with given input array
 * @tags user
 * @see http://localhost:3000/swagger#/user/createUsersWithListInput
 */
export const userCreateWithListPostApi = new RequestBuilder<
  userCreateWithListPostApi.Req,
  userCreateWithListPostApi.Res
>({
  url: "/user/createWithList",
  method: "post",
});

export namespace userCreateWithListPostApi {
  export interface Req {}

  export type Res = any;
}
