name: Publish

on:
  push:
    branches:
      - release
env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install
        run: pnpm i

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Build
        run: pnpm build
