import { defineConfig } from 'tsdown';

export default defineConfig({
  name: 'tools',
  target: 'esnext',
  platform: 'neutral',
  sourcemap: true,
  tsconfig: './tsconfig.json',
  format: 'esm',
  dts: true,
  unbundle: true,
  clean: true,
  entry: {
    index: 'src/index.ts',
    'factory/createStateContext': 'src/factory/createStateContext.tsx',
    'factory/fieldsMap': 'src/factory/fieldsMap.tsx',
    'factory/mapProps': 'src/factory/mapProps.tsx',
    numbro: 'src/numbro/index.ts',
    'rq/index': 'src/rq/index.ts',
    'rq/index.react-server': 'src/rq/index.react-server.ts',
    'rq/RequestBuilder': 'src/rq/RequestBuilder.ts',
    'rq/RequestBuilder.base': 'src/rq/RequestBuilder.base.ts',
    'rq/RequestBuilder.react-server': 'src/rq/RequestBuilder.react-server.ts',
    'rq/createApi': 'src/rq/createApi.ts',
    'rq/defaultQueryClient': 'src/rq/defaultQueryClient.ts',
    'rq/options': 'src/rq/options.ts',
    'shared/index': 'src/shared/index.ts',
    'shared/OptionalKeys': 'src/shared/OptionalKeys.ts',
    'shared/Overwrite': 'src/shared/Overwrite.ts',
    'shared/Print': 'src/shared/Print.ts',
    'storage/index': 'src/storage/index.ts',
    'storage/cookie': 'src/storage/cookie.ts',
    'store/index': 'src/store/index.ts',
  },
});
