import SwaggerParser from "@apidevtools/swagger-parser";
import { camelCase, isPlainObject, merge } from "es-toolkit";
import { compile } from "json-schema-to-typescript";
import { AsyncLocalStorage } from "node:async_hooks";
import fs from "node:fs/promises";
import { OpenAPIV3, type OpenAPI } from "openapi-types";
import * as os from "os";
import pMap from "p-map";
import path from "path";
import { createLogger } from "../../shared";
import { ApiConfig, getConfig } from "../../shared/config";
import { promptApiConfigEnable } from "../../shared/promptConfigEnable";

const log = createLogger("generateApi");

export const asyncLocalStorage = new AsyncLocalStorage<{
  parsed: OpenAPIV3.Document;
  parser: SwaggerParser;
}>();

function isV3(doc: OpenAPI.Document | undefined): doc is OpenAPIV3.Document {
  if (doc) {
    return "components" in doc;
  }
  return false;
}

export async function generateApi() {
  const config = await getConfig();
  const apiConfigs = await promptApiConfigEnable(config.api);

  for (const apiConfig of apiConfigs) {
    log.info(`清除旧的 api 文件：${apiConfig.output}`);
    await fs.rm(apiConfig.output!, { recursive: true, force: true });
    await fs.mkdir(apiConfig.output!, { recursive: true });
  }

  for (const apiConfig of apiConfigs) {
    log.info("开始解析 %s", apiConfig.swaggerJSONPath);
    const dereferenceConfig = merge(
      {
        resolve: {
          http: {
            timeout: 30 * 1000,
          },
        },
      },
      apiConfig.dereferenceSwaggerConfig || {},
    );
    const parser = new SwaggerParser();

    const parsed = await parser.bundle(
      apiConfig.swaggerJSONPath,
      dereferenceConfig,
    );

    const state = {
      // only support v3
      parsed: parsed as OpenAPIV3.Document,
      parser,
    };
    await asyncLocalStorage.run(state, async () => {
      await pMap(
        Object.entries(parsed.paths!),
        async ([url, pathItemObject]) => {
          log.info("开始生成 %s", url);
          if (pathItemObject) {
            await pMap(
              ["get", "put", "post", "delete", "patch"],
              async (method) => {
                const operationObject = pathItemObject[method];
                if (operationObject) {
                  const code = await generateApiRequestCode({
                    url: url,
                    method: method,
                    operationObject: operationObject,
                    apiConfig,
                  });
                  const outputPath = path
                    .join(
                      apiConfig.output!,
                      url,
                      apiConfig.enableTs ? `${method}.ts` : `${method}.js`,
                    )
                    .replace(/:/g, "_");
                  await fs.mkdir(path.dirname(outputPath), {
                    recursive: true,
                  });
                  await fs.writeFile(outputPath, code);
                }
              },
            );
          }
        },
      );
    });
    if (apiConfig.codeFormatterCmd) {
      const { exec } = await import("child_process");
      await new Promise<void>((resolve, reject) => {
        exec(
          `${apiConfig.codeFormatterCmd} ${apiConfig.output!}/**`,
          (error) => {
            if (error) {
              console.warn(`Code formatting failed: ${error.message}`);
            }
            resolve();
          },
        );
      });
    }
  }

  log.info("generateApi Done");
}

/**
 * 根据请求方法，生成请求代码
 */
export async function generateApiRequestCode(options: {
  url: string;
  method: string;
  operationObject: OpenAPIV3.OperationObject;
  apiConfig: ApiConfig;
}): Promise<string> {
  const { method, operationObject, apiConfig } = options;

  const url = (() => {
    if (typeof apiConfig.urlTransformer === "string") {
      return `${apiConfig.urlTransformer}${options.url}`;
    }
    if (typeof apiConfig.urlTransformer === "function") {
      return apiConfig.urlTransformer(options.url);
    }
    return options.url;
  })();

  const seeUrl = apiConfig.swaggerUiUrl
    ? `${apiConfig.swaggerUiUrl}#/${encodeURIComponent(
        `${operationObject.tags?.join("/") ?? ""}/${
          operationObject.operationId
        }`,
      )}`
    : "";

  // 生成的请求构造器的名称，需要使用原始 url
  let requestBuilderName = camelCase(`${options.url}_${method}_api`);

  // 判断是否有效的 js 变量
  if (!/^[a-zA-Z_$][0-9a-zA-Z_$]*$/.test(requestBuilderName)) {
    // 不是有效的 js 变量，使用 _ + 数字
    requestBuilderName = `_${requestBuilderName}`;
  }

  //#region url 上参数 例如 /api/v1/users/{userId}
  const urlPathParams = getUrlPathParams(
    (operationObject.parameters as never) ?? [],
  );
  const urlPathParamsCode = urlPathParams.length
    ? `urlPathParams: ${JSON.stringify(urlPathParams)},`
    : "";
  //#endregion

  let code: string[] = [
    "// do not edit this file manually, it will be overwritten by @dune2/cli",
    apiConfig.RequestBuilderImportPath!,
    apiConfig.queryClientImportPath!,

    "/**",
    `  * ${operationObject.summary}`,
    `  * @tags ${operationObject.tags?.join(",")}`,
    seeUrl && `  * @see ${seeUrl}`,
    `  */`,
  ].filter(Boolean);

  // builder 代码
  let builderCode = `\
export const ${requestBuilderName} = new RequestBuilder({
  url: '${url}',
  method: '${method}',
  ${urlPathParamsCode}
  ${apiConfig.queryClientImportPath ? "queryClient," : ""}
});`
    // 移除空行
    .replace(/,\n\s*}/, "," + os.EOL + "}");
  if (apiConfig.enableTs) {
    builderCode = builderCode.replace(
      "new RequestBuilder(",
      `new RequestBuilder<${requestBuilderName}.Req, ${requestBuilderName}.Res>(`,
    );
  }
  code.push(builderCode);

  if (apiConfig.enableTs) {
    const [requestParamsTypeCode, responseParamsTypeCode] = await Promise.all([
      // 请求参数类型
      compileRequestParams(operationObject),
      // 响应参数类型
      compileResponseParams(operationObject, apiConfig),
    ]);

    code.push(`
export namespace ${requestBuilderName} {
 ${requestParamsTypeCode.code}
 
 ${responseParamsTypeCode}
};`);
  }

  return code.join(os.EOL);
}

function getUrlPathParams(parameters: OpenAPIV3.ParameterObject[]) {
  return parameters
    .filter((item) => item.in === "path")
    .map((item) => item.name);
}

/**
 * 这个方法还不完善，只能处理简单的请求参数
 */
async function compileRequestParams(
  operationObject: OpenAPIV3.OperationObject,
) {
  const store = asyncLocalStorage.getStore();
  const schemaOrRefObject = (() => {
    if (operationObject.requestBody) {
      if ("$ref" in operationObject.requestBody) {
        return operationObject.requestBody;
      }
      return operationObject.requestBody.content["application/json"].schema;
    }
    if (operationObject.parameters) {
      const extraProperties = {};
      const parameters: OpenAPIV3.ParameterObject[] = [];
      (operationObject.parameters as OpenAPIV3.ParameterObject[]).forEach(
        (item) => {
          if (!["query", "path"].includes(item.in)) {
            return;
          }
          if (
            item.schema &&
            "type" in item.schema &&
            item.schema.type === "object"
          ) {
            // swagger get 请求上 有些参数是 object 类型 应该拍平
            Object.assign(
              extraProperties,
              (item.schema as OpenAPIV3.SchemaObject).properties || {},
            );
          } else {
            parameters.push(item);
          }
        },
      );
      // 必填参数中忽略 分页相关的参数
      const required = parameters
        .filter(
          (p) =>
            p.required && !["pageNum", "pageSize", "count"].includes(p.name),
        )
        .map((p) => p.name);
      const properties = Object.fromEntries(
        parameters
          // 后端 swagger 可能出现没有 schema 的情况，这里过滤掉
          .filter((p) => !!p.schema)
          .map((p) => {
            const schema = p.schema;
            return [
              p.name,
              {
                ...schema,
                description: p.description,
                // enum: schema.enum ?? [],
              },
            ];
          }),
      );
      return {
        required,
        type: "object",
        properties: { ...properties, ...extraProperties },
      };
    }
  })();

  const finalSchema = isPlainObject(schemaOrRefObject)
    ? Object.assign(
        {
          components: store?.parsed.components,
        },
        "$ref" in schemaOrRefObject
          ? store?.parser.$refs.get(schemaOrRefObject.$ref)
          : schemaOrRefObject,
      )
    : void 0;

  let code = "";
  if (finalSchema) {
    try {
      code = await compile(finalSchema as never, "Req", {
        bannerComment: "",
        ignoreMinAndMaxItems: !!1,
        additionalProperties: false,
        unknownAny: false,
        // format: false,
      });
    } catch (e) {
      log.error("生成请求参数类型失败，请检查 %o", {
        summary: operationObject.summary,
        message: e.message,
        operationId: operationObject.operationId,
      });
    }
  }

  return {
    code: code || "export type Req = any;",
  };
}

async function compileResponseParams(
  operationObject: OpenAPIV3.OperationObject,
  apiConfig: ApiConfig,
) {
  const temp = operationObject.responses["200"] as OpenAPIV3.ResponseObject;
  let code = "";
  if (temp?.content) {
    // FIXME: 可能需要处理其他的 content 类型
    const temp2 = temp.content["application/json"] || temp.content["*/*"];
    //let schema = temp2.schema;
    //@ts-expect-error TODO: 待修复类型
    let schema = apiConfig.responseSchemaTransformer!(temp2.schema);
    if (schema) {
      const store = asyncLocalStorage.getStore();

      const schema2 = (() => {
        if ("$ref" in schema && store?.parser && isV3(store.parsed)) {
          let r = store?.parser.$refs.get(schema.$ref);
          // @ts-expect-error TODO: 待修复类型
          r = apiConfig.responseSchemaTransformer!(r);
          if (isPlainObject(r)) {
            if ("$ref" in r) {
              r = store?.parser.$refs.get(r.$ref as string);
            }

            if (isPlainObject(r)) {
              return {
                ...r,
                components: store?.parsed.components,
              };
            }
          }
          log.error(`unknown other types`);
          return;
        }
        return schema;
      })();

      if (!schema2) {
        log.error(`can not found schema to generate response code`);
      }

      try {
        code = await compile(schema2, "Res", {
          bannerComment: "",
          ignoreMinAndMaxItems: !!1,
          additionalProperties: false,
          unknownAny: false,
          // format: false,
        });

        // 通过响应数据判断是否是分页查询接口
        const isPageSearchResponse = (data: any) => {
          // 有 result 字段且为数组，就认为是分页查询接口
          return (
            data.type === "object" && data.properties?.result?.type === "array"
          );
        };

        // 新增后端分页查询返回的数据类型
        if (isPageSearchResponse(schema)) {
          code += `${os.EOL}export type ResultItem = Res['result'][0]`;
        }
      } catch (e) {
        log.error("转换响应参数类型失败，请检查 %o", {
          summary: operationObject.summary,
          error: e.message,
          operationId: operationObject.operationId,
        });
      }
    } else {
      log.error("responseSchemaTransformer 返回值为空，请检查");
    }
  }

  return code ? code : "export type Res = any;";
}
