import * as os from 'os';
import { camelCase } from 'es-toolkit';
import type { OpenAPIV3 } from 'openapi-types';
import type { ApiConfig } from '../../shared/config';
import { compileRequestParams, compileResponseParams } from './typeCompiler';

/**
 * 根据请求方法，生成请求代码
 */
export async function generateApiRequestCode(options: {
  url: string;
  method: string;
  operationObject: OpenAPIV3.OperationObject;
  apiConfig: ApiConfig;
}): Promise<string> {
  const { method, operationObject, apiConfig } = options;

  const url = (() => {
    if (typeof apiConfig.urlTransformer === 'string') {
      return `${apiConfig.urlTransformer}${options.url}`;
    }
    if (typeof apiConfig.urlTransformer === 'function') {
      return apiConfig.urlTransformer(options.url);
    }
    return options.url;
  })();

  const seeUrl = apiConfig.swaggerUiUrl
    ? `${apiConfig.swaggerUiUrl}#/${encodeURIComponent(
        `${operationObject.tags?.join('/') ?? ''}/${
          operationObject.operationId
        }`,
      )}`
    : '';

  // 生成的请求构造器的名称，需要使用原始 url
  let requestBuilderName = camelCase(`${options.url}_${method}_api`);

  // 判断是否有效的 js 变量
  if (!/^[a-zA-Z_$][0-9a-zA-Z_$]*$/.test(requestBuilderName)) {
    // 不是有效的 js 变量，使用 _ + 数字
    requestBuilderName = `_${requestBuilderName}`;
  }

  //#region url 上参数 例如 /api/v1/users/{userId}
  const urlPathParams = getUrlPathParams(
    (operationObject.parameters as never) ?? [],
  );
  const urlPathParamsCode = urlPathParams.length
    ? `urlPathParams: ${JSON.stringify(urlPathParams)},`
    : '';
  //#endregion

  let code: string[] = [
    '// do not edit this file manually, it will be overwritten by @dune2/cli',
    apiConfig.RequestBuilderImportPath!,
    apiConfig.queryClientImportPath!,

    '/**',
    `  * ${operationObject.summary}`,
    `  * @tags ${operationObject.tags?.join(',')}`,
    seeUrl && `  * @see ${seeUrl}`,
    `  */`,
  ].filter(Boolean);

  // builder 代码
  let builderCode = `\
export const ${requestBuilderName} = new RequestBuilder({
  url: '${url}',
  method: '${method}',
  ${urlPathParamsCode}
  ${apiConfig.queryClientImportPath ? 'queryClient,' : ''}
});`
    // 移除空行
    .replace(/,\n\s*}/, ',' + os.EOL + '}');
  if (apiConfig.enableTs) {
    builderCode = builderCode.replace(
      'new RequestBuilder(',
      `new RequestBuilder<${requestBuilderName}.Req, ${requestBuilderName}.Res>(`,
    );
  }
  code.push(builderCode);

  if (apiConfig.enableTs) {
    const [requestParamsTypeCode, responseParamsTypeCode] = await Promise.all([
      // 请求参数类型
      compileRequestParams(operationObject),
      // 响应参数类型
      compileResponseParams(operationObject, apiConfig),
    ]);

    code.push(`
export namespace ${requestBuilderName} {
 ${requestParamsTypeCode.code}
 
 ${responseParamsTypeCode}
};`);
  }

  return code.join(os.EOL);
}

function getUrlPathParams(parameters: OpenAPIV3.ParameterObject[]) {
  return parameters
    .filter((item) => item.in === 'path')
    .map((item) => item.name);
}
